import { LegalPage } from '@/components/LegalPage'

const TERMS = `
## 1. Agreement and Acceptance

By accessing or using the Gradient platform, available at gradient.app (the **"Service"**), you agree to be bound by these Terms of Service (**"Terms"**). Your use of the Service, creation of an account, or clicking any "I agree" or "Continue" button constitutes a legally binding electronic signature under the Electronic Signatures in Global and National Commerce Act (E-SIGN Act). If you do not agree, do not use the Service.

These Terms are between you and **Josh Laubach, doing business as Gradient** ("Gradient," "we," "our," or "us"), a California sole proprietorship.

---

## 2. Eligibility and Age Requirements

You must be at least **13 years of age** to use the Service. Use by children under 13 is strictly prohibited and constitutes a material breach of these Terms. If we discover or have reasonable grounds to believe a user is under 13, we will immediately suspend the account and delete all associated data.

Users aged 13–17 must have verifiable parental or legal guardian consent before creating an account. By creating an account on behalf of a minor, the parent or guardian agrees to these Terms on the minor's behalf and accepts full responsibility for the minor's use of the Service.

---

## 3. Account Registration and Security

You agree to:

- Provide accurate, current, and complete information during registration
- Maintain only one account per natural person
- Keep your credentials confidential and not share them with any other person
- Notify us immediately at joshlaubach.mathtutor@gmail.com of any unauthorized access to your account

Accounts created using false information, automated scripts, or for the purpose of circumventing usage limits are prohibited and will be permanently terminated without refund. We reserve the right to reclaim any username that impersonates another person or entity.

---

## 4. Acceptable Use

You may use the Service solely for lawful, personal educational purposes. You agree not to:

- Use the Service on behalf of a third party without explicit written authorization
- Represent AI-generated content produced by the Service as your own original work in an academic or professional setting where such representation is prohibited
- Access or attempt to access any account, system, or data that is not yours
- Interfere with, degrade, or disrupt the integrity or performance of the Service

---

## 5. Prohibited Conduct

The following conduct is **strictly prohibited** and may result in immediate termination, civil liability, or criminal referral:

### 5.1 Bots and Automation
- Accessing the Service using any automated tool, script, bot, crawler, scraper, or non-human agent
- Programmatically creating accounts, generating problems, or harvesting content at scale
- Circumventing or attempting to circumvent any rate limit, CAPTCHA, fingerprinting, or abuse-detection mechanism
- Using the Service, its API, or its AI-generated output to train, fine-tune, benchmark, or evaluate any competing artificial intelligence or machine learning model

### 5.2 Fraud and Billing Abuse
- Creating multiple free-tier accounts to reset daily problem limits or circumvent subscription restrictions (account cycling)
- Sharing paid account credentials with non-paying users
- Filing chargebacks or payment disputes for services already rendered without first contacting us at joshlaubach.mathtutor@gmail.com
- Using stolen, fraudulent, or unauthorized payment methods
- Exploiting promotional codes beyond one per person per promotion, or transferring codes to others

### 5.3 Security and System Abuse
- Conducting unauthorized penetration testing, vulnerability scanning, or fuzzing against any part of the Service or its infrastructure
- Attempting to inject malicious input into AI prompts (prompt injection), extract system prompts, or otherwise manipulate the AI outside its intended educational function
- Exploiting any bug, vulnerability, or unintended feature to gain unauthorized access or capabilities (including bypassing subscription tier gates or calculator access controls)
- Reverse engineering, decompiling, or disassembling any portion of the Service

### 5.4 Content and IP Abuse
- Systematically downloading, reproducing, or redistributing problems, lesson notes, solutions, or other platform content
- Reselling or sublicensing any content generated by or accessed through the Service without a separate commercial license
- Publishing or distributing AI-generated content from the Service in third-party test-prep products, tutoring services, or publications

### 5.5 Circumvention of Technical Measures
Bypassing any technological measure that controls access to or use of the Service — including subscription tier enforcement, calculator level gates, or content access restrictions — is a violation of the Digital Millennium Copyright Act (DMCA), 17 U.S.C. § 1201, in addition to these Terms. We may seek statutory damages of up to $2,500 per act of circumvention under applicable law.

---

## 6. AI-Generated Content

The Service uses artificial intelligence, including models provided by Anthropic, PBC, to generate math problems, hints, step-by-step solutions, and lesson notes. **AI-generated content may contain mathematical errors, omissions, or inaccuracies.** We make no representation that any AI-generated content is correct, complete, or suitable for any particular academic purpose, exam, or curriculum standard.

You use AI-generated content at your own risk. Gradient is a supplemental learning tool and is not a substitute for a qualified teacher, tutor, or textbook. We are not responsible for any academic outcomes, exam results, or disciplinary consequences arising from reliance on AI-generated content.

---

## 7. Subscription and Billing

### 7.1 Plans and Payment
Access to certain features requires a paid subscription. Billing is processed by Stripe, Inc. By subscribing, you authorize Stripe to charge your payment method on a recurring basis. You agree to Stripe's terms of service in addition to these Terms.

### 7.2 Auto-Renewal
All paid plans **automatically renew** at the end of each billing period unless you cancel before the renewal date. Cancellation stops future charges but does not entitle you to a refund for the current period already paid.

### 7.3 Price Changes
We may change subscription prices with **30 days' prior notice** via email or in-app notification. Your continued use of the Service after the notice period constitutes acceptance of the new pricing.

### 7.4 Refunds
All purchases are final. We do not provide refunds except where required by applicable law or at our sole discretion in cases of verified billing errors.

### 7.5 Free Tier
Free-tier usage is subject to daily and monthly limits that we may change at any time. Abuse of the free tier, including account cycling, will result in permanent suspension.

---

## 8. Intellectual Property

### 8.1 Our IP
All content, software, design, trademarks, AI prompts, curriculum structure, and other materials on or constituting the Service are the intellectual property of Josh Laubach d/b/a Gradient or our licensors. No license to our IP is granted by these Terms except the limited right to access the Service for personal educational use.

### 8.2 Feedback License
If you submit any feedback, bug reports, feature requests, or suggestions to us, you grant us a perpetual, irrevocable, worldwide, royalty-free license to use, modify, and incorporate that feedback into the Service without compensation to you.

### 8.3 No Implied License
Nothing in these Terms grants you any right to use our trademarks, logos, domain names, or brand features.

---

## 9. User-Generated Content

If you submit any content to the Service — including assignment questions, classroom notes, or student submissions — you grant Gradient a non-exclusive, worldwide, royalty-free license to store, display, and process that content solely to provide the Service. You represent that you have all necessary rights to submit such content. We may remove any user-submitted content at any time without notice or liability.

---

## 10. Student Data and Educational Records

Our collection and use of student data is governed by our **Privacy Policy** and, for institutional users, our **Data Processing Agreement (DPA)**. We comply with the Family Educational Rights and Privacy Act (FERPA), the Children's Online Privacy Protection Act (COPPA), and the California Consumer Privacy Act (CCPA/CPRA) to the extent each applies.

Schools and teachers who use the Service with students must execute our DPA before enabling classroom features. By enabling classroom features without executing a DPA, you represent that you have the legal authority to authorize our data processing on behalf of your institution.

---

## 11. Third-Party Services

The Service integrates with the following third-party providers whose separate terms govern their respective services:

- **Clerk, Inc.** — authentication and identity management
- **Stripe, Inc.** — payment processing and subscription management
- **Anthropic, PBC** — AI model inference

We are not responsible for the availability, accuracy, or conduct of these third-party services. Outages, errors, or data incidents attributable to these providers do not constitute a breach of these Terms by Gradient.

---

## 12. Security

You agree not to conduct unauthorized security testing against the Service. If you discover a security vulnerability, you agree to disclose it responsibly by emailing joshlaubach.mathtutor@gmail.com before any public disclosure. Unauthorized disclosure of security vulnerabilities is a breach of these Terms.

In the event of a data breach affecting your personal information, we will notify you within a commercially reasonable time in accordance with applicable California law.

---

## 13. Privacy

Your use of the Service is subject to our **Privacy Policy**, which is incorporated into these Terms by reference. By using the Service, you consent to our collection and use of your data as described in the Privacy Policy.

---

## 14. Disclaimers

**THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.**

We do not guarantee any minimum uptime or service level. Scheduled and unscheduled maintenance may cause temporary unavailability without notice or credit.

New and beta features — including but not limited to the calculator widget, CAS functionality, and AI tutoring — are provided without warranty and may be modified, restricted, or discontinued at any time.

---

## 15. Limitation of Liability

**TO THE MAXIMUM EXTENT PERMITTED BY CALIFORNIA LAW, GRADIENT'S TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING OUT OF OR RELATED TO THESE TERMS OR YOUR USE OF THE SERVICE SHALL NOT EXCEED THE GREATER OF (A) $100 OR (B) THE TOTAL FEES YOU PAID TO GRADIENT IN THE THREE MONTHS IMMEDIATELY PRECEDING THE CLAIM.**

IN NO EVENT SHALL GRADIENT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, DATA LOSS, OR ACADEMIC HARM, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

---

## 16. Indemnification

You agree to defend, indemnify, and hold harmless Josh Laubach d/b/a Gradient from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or related to: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any applicable law or third-party right; or (d) any content you submit to the Service.

---

## 17. Dispute Resolution — Mandatory Arbitration

> **PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS.**

### 17.1 Informal Resolution First
Before initiating arbitration, you agree to first contact us at joshlaubach.mathtutor@gmail.com and describe your dispute in detail. We will attempt to resolve it informally within **60 days**. If the dispute is not resolved within that period, either party may proceed to arbitration.

### 17.2 Binding Arbitration
If informal resolution fails, any dispute, claim, or controversy arising out of or relating to these Terms or the Service will be resolved by **binding arbitration** administered by the American Arbitration Association (AAA) under its Consumer Arbitration Rules, except as modified by these Terms. The arbitration shall be conducted in California or, at your election if you are a California resident, in the county of your residence.

For claims under $10,000, Gradient will pay all AAA filing fees. The arbitrator's decision shall be final and binding and may be entered as a judgment in any court of competent jurisdiction.

### 17.3 Exceptions
Either party may seek emergency injunctive relief in a court of competent jurisdiction to prevent irreparable harm, including claims for intellectual property infringement or unauthorized access to systems.

---

## 18. Class Action Waiver

> **YOU AND GRADIENT EACH WAIVE THE RIGHT TO A TRIAL BY JURY AND THE RIGHT TO PARTICIPATE IN ANY CLASS, COLLECTIVE, OR REPRESENTATIVE ACTION OR PROCEEDING. ALL CLAIMS MUST BE BROUGHT IN AN INDIVIDUAL CAPACITY. THIS WAIVER IS A MATERIAL TERM OF THESE TERMS AND CANNOT BE SEVERED FROM THE ARBITRATION AGREEMENT.**

If this waiver is found unenforceable for a particular claim, that claim must be litigated in court and severed from any arbitration proceeding.

---

## 19. Governing Law

These Terms shall be governed by and construed in accordance with the laws of the **State of California**, without regard to conflict-of-law principles. Any court proceedings permitted under these Terms shall be brought exclusively in the state or federal courts located in California.

---

## 20. Export Controls

You may not use or access the Service if you are located in, or are a national or resident of, any country subject to U.S. economic sanctions or export control laws, including countries on the U.S. Office of Foreign Assets Control (OFAC) sanctions list. You represent and warrant that you are not such a person and that your use of the Service will not violate any applicable export control laws.

---

## 21. Modifications

We may update these Terms at any time. For material changes, we will provide at least **30 days' prior notice** via email or in-app notification. Your continued use of the Service after notice constitutes acceptance. If you do not agree to the updated Terms, you must stop using the Service and may cancel your subscription.

---

## 22. Assignment

You may not assign or transfer these Terms or any rights or obligations hereunder without our prior written consent. We may assign these Terms freely, including in connection with a merger, acquisition, or sale of assets, without notice to you.

---

## 23. Force Majeure

Gradient shall not be liable for any failure or delay in performance caused by circumstances beyond our reasonable control, including acts of God, internet infrastructure failures, third-party API outages (including Anthropic, Clerk, or Stripe), government actions, natural disasters, or cyberattacks.

---

## 24. Miscellaneous

- **Statute of Limitations.** Any claim arising out of or related to these Terms must be brought within **one year** of the date the claim arose, regardless of any longer period permitted by applicable law.
- **Severability.** If any provision of these Terms is found unenforceable, the remaining provisions continue in full force.
- **No Waiver.** Our failure to enforce any provision of these Terms on one occasion does not waive our right to enforce it on any other occasion.
- **Survival.** Sections 5, 8, 14, 15, 16, 17, 18, 19, and 24 survive termination of these Terms.
- **Entire Agreement.** These Terms, together with our Privacy Policy and any applicable Data Processing Agreement, constitute the entire agreement between you and Gradient regarding the Service.
- **Attorneys' Fees.** In any arbitration or court proceeding in which Gradient is the prevailing party, we shall be entitled to recover our reasonable attorneys' fees and costs.
- **Contact.** Questions about these Terms should be directed to joshlaubach.mathtutor@gmail.com.
`

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      subtitle="Please read these terms carefully before using Gradient."
      effectiveDate="May 11, 2026"
      lastUpdated="May 11, 2026"
      content={TERMS}
    />
  )
}
